[project]
name = "hadronic-blazar-model"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "astropy>=5.2.2",
    "jupyter",
    "matplotlib>=3.7.5",
    "scipy>=1.10.1",
]
